<!DOCTYPE html>
<html>
<head>
    <title>Surat {{ $surat->nomor_surat }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .letterhead {
            text-align: center;
            margin-bottom: 20px;
        }
        .letterhead img {
            width: 100px; /* Sesuaikan ukuran logo */
        }
        .date {
            text-align: right;
            margin-bottom: 10px;
        }
        .reference {
            margin-bottom: 10px;
        }
        .recipient {
            margin-bottom: 10px;
        }
        .salutation {
            margin-bottom: 10px;
        }
        .body {
            margin-bottom: 20px;
            text-align: justify;
            line-height: 1.5;
        }
        .closing {
            margin-bottom: 20px;
        }
        .signature {
            text-align: left;
            margin-bottom: 20px;
        }
        .footer {
            text-align: center;
            font-size: 12px;
        }
        h2 {
            font-size: 18px;
            margin: 0;
        }
        p {
            margin: 5px 0;
        }
        .reference p, .recipient p, .salutation p, .body p, .closing p, .signature p {
            margin: 0;
        }
    </style>
</head>
<body>
    <div class="letterhead">
        <img src="{{ public_path('images/koni-logo.jpg') }}" alt="KONI Logo"><!-- Ganti dengan path logo yang benar -->
        <h2>Komite Olahraga Nasional Indonesia Kabupaten Sleman</h2>
        <p>Alamat: Jl. Magelang KM 10, Sleman, DIY</p>
        <p>Telepon: (0274) 123456</p>
        <p>Email: koni.sleman@example.com</p>
    </div>
    <div class="date">
        <p>Sleman, {{ \Carbon\Carbon::parse($surat->tanggal_surat)->translatedFormat('d F Y') }}</p>
    </div>
    <div class="reference">
        <p>Nomor: {{ $surat->nomor_surat }}</p>
        <p>Lampiran: {{ $surat->lampiran ?? 'Permohonan Data Kerja Praktik' }}</p>
        <p>Perihal: {{ $surat->perihal }}</p>
    </div>
    <div class="recipient">
        <p>{{ $surat->tujuan }}</p>
    </div>
    <div class="salutation">
        <p>Salam Olahraga,</p>
    </div>
    <div class="body">
        {!! nl2br(e($surat->isi)) !!}
    </div>
    <div class="closing">
        <p>Demikian atas perhatian dan kerjasamanya diucapkan terima kasih.</p>
    </div>
    <div class="signature">
        <p>Ketua Umum,</p>
        <br><br><br>
        <p>H. Joko Hastaryo, M.Kes</p>
    </div>
    <div class="footer">
        <p>Generated by Sistem Cabor Sleman</p>
    </div>
</body>
</html>